# Generated by Django 4.0.5 on 2022-06-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planid', models.CharField(max_length=50)),
                ('planname', models.CharField(max_length=50)),
                ('lowtn', models.CharField(max_length=50)),
                ('midtn', models.CharField(max_length=50)),
                ('hightn', models.CharField(max_length=50)),
                ('lbp', models.CharField(max_length=50)),
                ('mbp', models.CharField(max_length=50)),
                ('Hbp', models.CharField(max_length=50)),
                ('lowam', models.CharField(max_length=50)),
                ('midam', models.CharField(max_length=50)),
                ('higham', models.CharField(max_length=50)),
            ],
        ),
    ]
