# Generated by Django 4.0.5 on 2022-06-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0002_rename_plans_brandplans_rename_hbp_brandplans_hbp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandplans',
            name='id',
        ),
        migrations.AlterField(
            model_name='brandplans',
            name='planid',
            field=models.CharField(max_length=50, primary_key=b'I01\n', serialize=False),
        ),
    ]
