# Generated by Django 4.0.5 on 2022-06-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0003_remove_brandplans_id_alter_brandplans_planid'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandplans',
            name='endDate',
            field=models.CharField(default=500, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandplans',
            name='quota',
            field=models.CharField(default=500, max_length=50),
            preserve_default=False,
        ),
    ]
