# Generated by Django 4.0.5 on 2022-06-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0004_brandplans_enddate_brandplans_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandplans',
            name='promPrcnt',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
