# Generated by Django 4.0.5 on 2022-06-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0005_brandplans_promprcnt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandplans',
            old_name='promPrcnt',
            new_name='hpromPrcnt',
        ),
        migrations.AddField(
            model_name='brandplans',
            name='lpromPrcnt',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandplans',
            name='mpromPrcnt',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
