# Generated by Django 4.0.5 on 2022-06-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0006_rename_promprcnt_brandplans_hpromprcnt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandplans',
            name='hpromPrcnt',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='brandplans',
            name='lpromPrcnt',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='brandplans',
            name='mpromPrcnt',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
