# Generated by Django 4.0.5 on 2022-06-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0007_alter_brandplans_hpromprcnt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandplans',
            name='htype',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='brandplans',
            name='ltype',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='brandplans',
            name='mtype',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
